wieght = int(input("Enter you weight in pounds"))
sun = 27.9*(wieght)
Mercury = .38*(wieght)
Venus = .91*(wieght)
Earth = 1*(wieght)
Moon = .17*(wieght)
Mars = .38*(wieght)
Jupiter = 2.54*(wieght)
Saturn = 1.08*(wieght)
Uranus =.91*(wieght)
Neptune = 1.19*(wieght)
Pluto = .06*(wieght)


print ('Your weight on the sun is:')
print(sun)
print ('Your weight on Mercury is:')
print(Mercury)
print ('Your weight on Venus is:')
print(Venus)
print ('Your weight on Earth is:')
print(Earth)
print ('Your weight on the Moon is:')
print(Moon)
print ('Your weight on Mars is:')
print(Mars)
print ('Your weight on Jupiter is:')
print(Jupiter)
print ('Your weight on Saturn is:')
print(Saturn)
print ('Your weight on Uranus is:')
print(Uranus)
print ('Your weight on Neptune is:')
print(Neptune)
print ('Your weight on Pluto is:')
print(Pluto)
